[package]
name = "ahoy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
cli-log = "2.1.0"
crossterm = "0.29.0"
env_logger = "0.11.8"
log = "0.4.28"
pollster = "0.4.0"
ratatui = "0.29.0"
wgpu = "26.0.1"
winit = { version = "0.30.12", features = ["android-native-activity"] }
